export const SEARCH_NEWS_REQUEST = "SEARCH_NEWS_REQUEST"
export const SEARCH_NEWS_SUCCESS = "SEARCH_NEWS_SUCCESS"

export const GET_NEWS_SOURCES_REQUEST = "GET_NEWS_SOURCES_REQUEST"
export const GET_NEWS_SOURCES_SUCCESS = "GET_NEWS_SOURCES_SUCCESS"

export const GET_NEWS_CATEGORIES_REQUEST = "GET_NEWS_CATEGORIES_REQUEST"
export const GET_NEWS_CATEGORIES_SUCCESS = "GET_NEWS_CATEGORIES_SUCCESS"
