export const SEARCH_NEWS_REQUEST = "SEARCH_NEWS_REQUEST"
export const SEARCH_NEWS_SUCCESS = "SEARCH_NEWS_SUCCESS"

export const NEXT_LIST_REQUEST = "NEXT_LIST_REQUEST"
export const NEXT_LIST_SUCCESS = "NEXT_LIST_SUCCESS"

export const GET_NEWS_SOURCES_REQUEST = "GET_NEWS_SOURCES_REQUEST"
export const GET_NEWS_SOURCES_SUCCESS = "GET_NEWS_SOURCES_SUCCESS"

export const GET_NEWS_CATEGORIES_REQUEST = "GET_NEWS_CATEGORIES_REQUEST"
export const GET_NEWS_CATEGORIES_SUCCESS = "GET_NEWS_CATEGORIES_SUCCESS"

export const SET_ALERT = "SET_ALERT"
export const REMOVE_ALERT = "REMOVE_ALERT"
